# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value
    app.file.twig.extension.class: AppBundle\Services\Helpers
services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.helpers:
            class: AppBundle\Services\Helpers
            arguments: ["null"]
            tags:
                - { name: twig.extension }