BackendBundle\Entity\CliSaldoAFavorLog:
    type: entity
    table: cli_saldo_a_favor_log
    id:
        idSaldoAFavorLog:
            type: bigint
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_saldo_a_favor_log
            generator:
                strategy: IDENTITY
    fields:
        idSaldoAFavor:
            type: bigint
            nullable: true
            options:
                unsigned: false
            column: id_saldo_a_favor
        idCliente:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: id_cliente
        motivo:
            type: string
            nullable: true
            length: 1000
            options:
                fixed: false
        monto:
            type: float
            nullable: true
            precision: 10
            scale: 2
        createdAt:
            type: datetime
            nullable: true
            column: created_at
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
        createdBy:
            type: bigint
            nullable: true
            options:
                unsigned: false
            column: created_by
        updatedBy:
            type: bigint
            nullable: true
            options:
                unsigned: false
            column: updated_by
    lifecycleCallbacks: {  }
