BackendBundle\Entity\GenTipoCompra:
    type: entity
    table: gen_tipo_compra
    indexes:
        created_by_idx:
            columns:
                - created_by
        updated_by_idx:
            columns:
                - updated_by
    id:
        idTipoCompra:
            type: smallint
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_tipo_compra
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        isActive:
            type: boolean
            nullable: true
            options:
                default: '1'
            column: is_active
        semanas:
            type: integer
            nullable: true
            options:
                unsigned: false
                default: '1'
        createdAt:
            type: datetime
            nullable: false
            column: created_at
        updatedAt:
            type: datetime
            nullable: false
            column: updated_at
        createdBy:
            type: bigint
            nullable: true
            options:
                unsigned: false
            column: created_by
        updatedBy:
            type: bigint
            nullable: true
            options:
                unsigned: false
            column: updated_by
    lifecycleCallbacks: {  }
