BackendBundle\Entity\GeoPaisEstado:
    type: entity
    table: geo_pais_estado
    indexes:
        id_pais_idx:
            columns:
                - id_pais
        created_by_idx:
            columns:
                - created_by
        updated_by_idx:
            columns:
                - updated_by
    uniqueConstraints:
        id_pais:
            columns:
                - id_pais
                - abreviatura
    id:
        idPaisEstado:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_pais_estado
            generator:
                strategy: IDENTITY
    fields:
        idPais:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: id_pais
        nombre:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
        abreviatura:
            type: string
            nullable: true
            length: 10
            options:
                fixed: false
        estado:
            type: boolean
            nullable: false
            options:
                default: '1'
        createdAt:
            type: datetime
            nullable: false
            column: created_at
        updatedAt:
            type: datetime
            nullable: false
            column: updated_at
        deletedAt:
            type: datetime
            nullable: true
            column: deleted_at
        createdBy:
            type: bigint
            nullable: true
            options:
                unsigned: false
            column: created_by
        updatedBy:
            type: bigint
            nullable: true
            options:
                unsigned: false
            column: updated_by
        deletedBy:
            type: bigint
            nullable: true
            options:
                unsigned: false
            column: deleted_by
    lifecycleCallbacks: {  }
