BackendBundle\Entity\Offices:
    type: entity
    table: offices
    id:
        officeid:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        officename:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
                default: ''
        country:
            type: string
            nullable: false
            length: 30
            options:
                fixed: false
        state:
            type: string
            nullable: false
            length: 30
            options:
                fixed: false
    lifecycleCallbacks: {  }
