BackendBundle\Entity\PermisionsUsers:
    type: entity
    table: permisions_users
    indexes:
        FK_permisions_users_permisions:
            columns:
                - id_permision
                - id_user
        FK_permision_users_users:
            columns:
                - id_user
    id:
        idPermisionUser:
            type: bigint
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_permision_user
            generator:
                strategy: IDENTITY
    fields:
        idUser:
            type: bigint
            nullable: false
            options:
                unsigned: false
            column: id_user
        idPermision:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: id_permision
        createdBy:
            type: bigint
            nullable: false
            options:
                unsigned: false
            column: created_by
        updatedBy:
            type: bigint
            nullable: false
            options:
                unsigned: false
            column: updated_by
        createdAt:
            type: datetime
            nullable: false
            column: created_at
        updatedAt:
            type: datetime
            nullable: false
            column: updated_at
    lifecycleCallbacks: {  }
