BackendBundle\Entity\Proveedor:
    type: entity
    table: proveedor
    indexes:
        id_ciudad_idx:
            columns:
                - id_ciudad
        created_by_idx:
            columns:
                - created_by
        updated_by_idx:
            columns:
                - updated_by
    id:
        idProveedor:
            type: bigint
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_proveedor
            generator:
                strategy: IDENTITY
    fields:
        idCiudad:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: id_ciudad
        codigo:
            type: string
            nullable: true
            length: 10
            options:
                fixed: false
        nombre:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        direccion:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
        telefono1:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        telefono2:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        zipCode:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: zip_code
        email:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        estado:
            type: boolean
            nullable: false
            options:
                default: '1'
        comentarios:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
        createdAt:
            type: datetime
            nullable: false
            column: created_at
        updatedAt:
            type: datetime
            nullable: false
            column: updated_at
        createdBy:
            type: bigint
            nullable: true
            options:
                unsigned: false
            column: created_by
        updatedBy:
            type: bigint
            nullable: true
            options:
                unsigned: false
            column: updated_by
        deletedAt:
            type: datetime
            nullable: true
            column: deleted_at
        deletedBy:
            type: bigint
            nullable: true
            options:
                unsigned: false
            column: deleted_by
    lifecycleCallbacks: {  }
