BackendBundle\Entity\Punchlist:
    type: entity
    table: punchlist
    id:
        idPunchlist:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_punchlist
            generator:
                strategy: IDENTITY
    fields:
        punchitems:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
                default: ''
        color:
            type: string
            nullable: false
            length: 7
            options:
                fixed: false
                default: ''
        inOrOut:
            type: boolean
            nullable: true
            column: in_or_out
    lifecycleCallbacks: {  }
