BackendBundle\Entity\TiendaCampos:
    type: entity
    table: tienda_campos
    id:
        idTiendaCampos:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_tienda_campos
            generator:
                strategy: IDENTITY
    fields:
        idUser:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: id_user
        idTienda:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: id_tienda
        campo:
            type: integer
            nullable: false
            options:
                unsigned: false
        createdAt:
            type: datetime
            nullable: false
            column: created_at
        updatedAt:
            type: datetime
            nullable: false
            column: updated_at
        createdBy:
            type: bigint
            nullable: false
            options:
                unsigned: false
            column: created_by
        updatedBy:
            type: bigint
            nullable: false
            options:
                unsigned: false
            column: updated_by
    lifecycleCallbacks: {  }
