BackendBundle\Entity\UseBenefit:
    type: entity
    table: use_benefit
    id:
        idUseBenefit:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_use_benefit
            generator:
                strategy: IDENTITY
    fields:
        idEmployee:
            type: string
            nullable: false
            length: 11
            options:
                fixed: false
            column: id_employee
        idBeneficio:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: id_beneficio
        quantity:
            type: integer
            nullable: false
            options:
                unsigned: false
        unitMeasure:
            type: string
            nullable: false
            length: 30
            options:
                fixed: false
            column: unit_measure
        startDate:
            type: datetime
            nullable: false
            column: start_date
        endDate:
            type: datetime
            nullable: false
            column: end_date
        createdAt:
            type: string
            nullable: false
            length: 30
            options:
                fixed: false
            column: created_at
    lifecycleCallbacks: {  }
